name: easy_hive
description: A wrapper of Hive database for easier & simpler usage.
version: 1.0.1
repository: https://github.com/simonpham/easy_hive

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  path_provider: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1
