name: easy_hive_encryption
description: Extension of easy_hive to support encryption.
version: 1.2.0
repository: https://github.com/simonpham/easy_hive

publish_to: none

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easy_hive: ^1.1.0
  hive: ^2.2.3

  flutter_secure_storage:
    git:
      url: https://github.com/simonpham/flutter_secure_storage.git
      ref: 0e5fef5ed55e5e43989143b0b2df3770c958b692
      path: flutter_secure_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
