name: easy_hive_encryption
description: A very good flutter package
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  easy_hive:
    path: ../easy_hive

  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
