name: easy_hive_encryption
description: Extension of easy_hive to support encryption.
version: 2.0.0
repository: https://github.com/simonpham/easy_hive

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easy_hive: ^2.0.0
  hive_ce: ^2.19.3

  flutter_secure_storage: 10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
